-- ============================================================
--  JOURNEYA - SUPABASE SCHEMA
--  Run this in the Supabase SQL editor once for your project.
-- ============================================================

-- Trips (weekend getaways)
create table if not exists public.trips (
  id          bigint generated by default as identity primary key,
  title       text not null,
  destination text,
  price       numeric,
  image       text,
  itinerary   text,
  inclusions  text,
  start_date  date,
  end_date    date,
  available   boolean default true,
  created_at  timestamptz default now()
);

-- Events (game nights / social gatherings)
create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  date        date,
  time        text,
  location    text,
  image       text,
  available   boolean default true,
  created_at  timestamptz default now()
);

-- Bookings (instant guest checkout - no accounts)
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  type        text not null,          -- 'trip' or 'event'
  item_id     bigint not null,        -- id of the trip/event
  item_title  text,                   -- snapshot of the title
  name        text not null,
  phone       text not null,
  email       text not null,
  created_at  timestamptz default now()
);

-- ============================================================
--  ROW LEVEL SECURITY
--  Public can READ trips/events and WRITE bookings (guest signup).
--  Admin mutates data via the Supabase dashboard / service role.
-- ============================================================
alter table public.trips   enable row level security;
alter table public.events  enable row level security;
alter table public.bookings enable row level security;

-- Anyone can read trips/events
create policy "public read trips"   on public.trips   for select using (true);
create policy "public read events"  on public.events  for select using (true);

-- Anyone can create a booking (guest checkout)
create policy "public insert bookings" on public.bookings for insert with check (true);

-- Admins can read bookings (for guest lists)
create policy "admin read bookings" on public.bookings for select using (auth.role() = 'service_role');