-- ============================================================
--  JOURNEYA - SUPABASE SCHEMA
--  Run this in the Supabase SQL editor once for your project.
-- ============================================================

-- Drop the old trips table if migrating from a previous version
drop table if exists public.trips;

-- Events (game nights / social gatherings)
create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  date        date,
  time        text,
  location    text,
  image       text,
  price       numeric,
  guidelines  text,
  available   boolean default true,
  created_at  timestamptz default now()
);

-- Migrate existing projects (safe to re-run)
alter table public.events add column if not exists price      numeric;
alter table public.events add column if not exists guidelines text;

-- Bookings (instant guest checkout - no accounts)
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  type        text not null,          -- 'event'
  item_id     bigint not null,        -- id of the event
  item_title  text,                   -- snapshot of the title
  name        text not null,
  phone       text not null,
  email       text not null,
  created_at  timestamptz default now()
);

-- ============================================================
--  ROW LEVEL SECURITY
--  Public can READ events and WRITE bookings (guest signup).
--  The admin portal (static site + password) writes events
--  through the same anon client, so public write policies are
--  granted here. Securing writes beyond this is documented in
--  the README (keep the password out of this static client).
-- ============================================================
alter table public.events  enable row level security;
alter table public.bookings enable row level security;

-- Anyone can read events
drop policy if exists "public read events" on public.events;
create policy "public read events" on public.events for select using (true);

-- Admin portal CRUD on events (static site, client-side auth)
drop policy if exists "admin insert events" on public.events;
create policy "admin insert events" on public.events for insert with check (true);
drop policy if exists "admin update events" on public.events;
create policy "admin update events" on public.events for update using (true);
drop policy if exists "admin delete events" on public.events;
create policy "admin delete events" on public.events for delete using (true);

-- Anyone can create a booking (guest checkout)
drop policy if exists "public insert bookings" on public.bookings;
create policy "public insert bookings" on public.bookings for insert with check (true);

-- The admin portal (static site + password) reads bookings through the
-- same anon client, so guests' bookings must be publicly readable. This
-- exposes names/phones to anyone with the API key (documented caveat).
drop policy if exists "admin read bookings"  on public.bookings;
drop policy if exists "public read bookings" on public.bookings;
create policy "public read bookings" on public.bookings for select using (true);