-- ============================================================
--  JOURNEYA - SUPABASE SCHEMA
--  Run this in the Supabase SQL editor once for your project.
--  Safe to re-run: it uses "if not exists" / "add column if not
--  exists" everywhere, so re-run it whenever the schema changes.
-- ============================================================

-- ============================================================
--  EVENTS (game nights / social gatherings)
--  Both "Regular" (uniform price) and "Professional" (multi-tier
--  tickets + custom fields) events live here.
-- ============================================================
create table if not exists public.events (
  id          bigint generated by default as identity primary key,
  title       text not null,
  event_type  text not null default 'regular',   -- 'regular' | 'professional'
  category    text,
  summary     text,
  description text,
  date        date,
  time        text,
  location    text,
  image       text,
  video       text,
  price       numeric,
  seats       bigint,                            -- optional total seats (seat-number assignment)
  refund_policy text,
  guidelines  text,
  is_private  boolean not null default false,
  share_token text,
  custom_fields jsonb not null default '[]',     -- [{label, required}] for professional events
  created_at  timestamptz default now()
);

-- Migrate existing projects (safe to re-run)
alter table public.events add column if not exists event_type    text;
alter table public.events add column if not exists category      text;
alter table public.events add column if not exists summary       text;
alter table public.events add column if not exists video         text;
alter table public.events add column if not exists seats         bigint;
alter table public.events add column if not exists refund_policy text;
alter table public.events add column if not exists is_private    boolean default false;
alter table public.events add column if not exists share_token   text;
alter table public.events add column if not exists custom_fields jsonb default '[]';

-- Unique share tokens (runs AFTER the migration above, so the column
-- exists whether the table is brand-new or pre-existing)
create unique index if not exists events_share_token_key
  on public.events (share_token) where share_token is not null;

-- ============================================================
--  TICKET TIERS (multi-tier pricing for professional events)
-- ============================================================
create table if not exists public.ticket_tiers (
  id         bigint generated by default as identity primary key,
  event_id   bigint not null references public.events(id) on delete cascade,
  name       text not null,
  price      numeric not null,
  created_at timestamptz default now()
);

-- ============================================================
--  BOOKINGS (instant guest checkout - no accounts)
--  One row per booking; "seats" = how many spots booked.
-- ============================================================
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  type        text not null,          -- 'event'
  item_id     bigint not null,        -- id of the event
  item_title  text,                   -- snapshot of the title
  name        text not null,
  phone       text not null,
  email       text not null,
  tier_id     bigint,                 -- for professional events
  tier_name   text,
  tier_price  numeric,
  custom_data jsonb not null default '{}',  -- answers to custom fields (IG, job, ...)
  seats       int not null default 1,
  total       numeric,
  created_at  timestamptz default now()
);

alter table public.bookings add column if not exists tier_id     bigint;
alter table public.bookings add column if not exists tier_name   text;
alter table public.bookings add column if not exists tier_price  numeric;
alter table public.bookings add column if not exists custom_data jsonb default '{}';
alter table public.bookings add column if not exists seats       int default 1;
alter table public.bookings add column if not exists total       numeric;

-- ============================================================
--  ADMIN USERS (Supabase Auth emails allowed to manage the site)
-- ============================================================
create table if not exists public.admin_emails (
  email       text primary key,
  created_at  timestamptz default now()
);

--  >>> If you have not added your email yet, this inserts it for you. <<<
--  >>> And it will also fix any existing rows with wrong case/spaces.   <<<
insert into public.admin_emails (email)
values (lower(btrim('journeya006@gmail.com')))
on conflict (email) do nothing;

update public.admin_emails set email = lower(btrim(email))
where email <> lower(btrim(email));

-- True if the current authenticated user's email is an allowed admin.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.admin_emails
    where lower(btrim(email)) = lower(coalesce(btrim(auth.jwt() ->> 'email'), ''))
  );
$$;

-- ============================================================
--  SHARE-LINK ACCESS (private events)
--  Private events are invisible on the public site, but a unique
--  token link can fetch them. These helpers let the public read a
--  private event ONLY when they hold the correct token.
-- ============================================================
create or replace function public.get_shared_event(p_token text)
returns table (
  id bigint, title text, event_type text, category text, summary text,
  description text, "date" date, "time" text, location text, image text, video text,
  price numeric, seats bigint, refund_policy text, guidelines text, custom_fields jsonb
)
language sql
security definer
set search_path = public
stable
as $$
  select id, title, event_type, category, summary, description, date, time, location,
         image, video, price, seats, refund_policy, guidelines, custom_fields
  from public.events
  where share_token = p_token
$$;

-- Ticket tiers for a private professional event, readable only by its token.
create or replace function public.get_shared_event_tiers(p_token text)
returns table (id bigint, name text, price numeric)
language sql
security definer
set search_path = public
stable
as $$
  select tt.id, tt.name, tt.price
  from public.ticket_tiers tt
  join public.events e on e.id = tt.event_id
  where e.share_token = p_token
$$;

-- ============================================================
--  ROW LEVEL SECURITY
--  Public can READ non-private events and WRITE bookings
--  (guest checkout - no login required to book).
--  Only authenticated admins can create/update/delete events,
--  manage tiers, or read the guest lists.
-- ============================================================
alter table public.events        enable row level security;
alter table public.ticket_tiers  enable row level security;
alter table public.bookings      enable row level security;
alter table public.admin_emails  enable row level security;

-- --- events ---
drop policy if exists "public read public events" on public.events;
create policy "public read public events" on public.events
  for select using (is_private = false or public.is_admin());

drop policy if exists "admin insert events" on public.events;
create policy "admin insert events" on public.events for insert with check (public.is_admin());
drop policy if exists "admin update events" on public.events;
create policy "admin update events" on public.events for update using (public.is_admin());
drop policy if exists "admin delete events" on public.events;
create policy "admin delete events" on public.events for delete using (public.is_admin());

-- --- ticket tiers (visible only for public events, or to admins) ---
drop policy if exists "public read tiers" on public.ticket_tiers;
create policy "public read tiers" on public.ticket_tiers for select
  using (
    public.is_admin()
    or exists (
      select 1 from public.events e
      where e.id = ticket_tiers.event_id and e.is_private = false
    )
  );
drop policy if exists "admin insert tiers" on public.ticket_tiers;
create policy "admin insert tiers" on public.ticket_tiers for insert with check (public.is_admin());
drop policy if exists "admin update tiers" on public.ticket_tiers;
create policy "admin update tiers" on public.ticket_tiers for update using (public.is_admin());
drop policy if exists "admin delete tiers" on public.ticket_tiers;
create policy "admin delete tiers" on public.ticket_tiers for delete using (public.is_admin());

-- --- bookings: anyone can create (guest checkout), only admins read ---
drop policy if exists "public insert bookings" on public.bookings;
create policy "public insert bookings" on public.bookings for insert with check (true);

drop policy if exists "admin read bookings"  on public.bookings;
drop policy if exists "public read bookings" on public.bookings;
create policy "admin read bookings" on public.bookings for select using (public.is_admin());

-- --- admin_emails ---
drop policy if exists "admin read admin_emails" on public.admin_emails;
create policy "admin read admin_emails" on public.admin_emails for select using (public.is_admin());

-- ============================================================
--  REFRESH THE API SCHEMA CACHE
--  After adding columns/tables, Supabase's PostgREST API keeps a
--  cached copy of the schema.  Without this, writes fail with:
--   "Could not find the '<column>' column of 'events' in the schema cache"
--  This reloads the cache so the new columns are immediately
--  available through the API.  (You can also run this command on
--  its own in the SQL editor - it is all you need in that case.)
-- ============================================================
select pg_notify('pgrst', 'reload schema');